name: Link Check

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --max-concurrency 4 --require-https README.md docs/**/*.md
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
